### Global gh-pages pre-amble
lsi: false
highlighter: pygments
markdown: redcarpet
exclude:
  - deck.js
  - asciidoctor-backends
keep_files:
  - deck.js
  - decks
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
