source "http://rubygems.org"

gem "public_suffix"
gem "guard-jekyll-plus"
gem "github-pages"
gem "asciidoctor"
gem "asciidoctor-diagram"
gem "pygments.rb"
gem "redcarpet"
gem "tilt"
gem "haml"
gem "nokogiri"
